import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbarr from "./component/Navbarr";
import Footerr from "./component/Footerr";
import SessionWraper from "./component/SessionWraper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get Me A Chai ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] `}
      >
        <SessionWraper>
          <Navbarr />
          <div className="min-h-screen bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] text-white ">
            {children}
          </div>
          <Footerr />
        </SessionWraper>
      </body>
    </html>
  );
}
